name: camera_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0
  path_provider: ^2.0.11
  image_picker: ^1.1.1
  video_player: ^2.2.19
  google_ml_kit: ^0.18.0
  native_opencv:
    path: ../native_opencv
  cupertino_icons: ^1.0.6
  permission_handler: ^11.3.1
  file_picker: ^5.0.1
  path: ^1.9.0
  ffmpeg_kit_flutter_min_gpl: ^6.0.3
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true



